Python wrapper for Gurobi Solver
guix-science/guix-science-nonfree pull request #3
Opened 2021-10-29 14:55 UTC by falloutphil

Hi,

We use Guix at Quantile Technologies and have been building out a private library of free and non-free software not yet in Guix proper.  Where possible we'd now like to share our efforts with the approriate public channels.

Here's a PR for the Python Wrapper around the the Gurobi Solver - which is a powerful peice of mathematical optimisation software.  The software is scientific, of academic (as well as commerical) interest, and non-free, so according to the guidelines I figured this would be a good place for it.

In terms of doing a PR I was unsure if you'd need to add my GPG public key to your channel keyring or similar to make it work - let me know if another way of submitting this is more apporpriate.

Note I have contacted Gurobi and been given their blessing to provide this package - I can provide evidence of this if neccessary.

Many Thanks,
Phil.

2021-11-11 12:08 UTC, PromyLOPh requested changes
Sorry for the delay, I’ve been ill and couldn’t review this in time.

Some lines use tabs and some use spaces. Please use spaces only. You don’t need to submit your GPG key. I’ll sign the final commit to master.

More comments inline.

2021-11-11 12:08 UTC, PromyLOPh commented on guix-science-nonfree/packages/gurobi.scm
> +    (license #f)))
Could you please use the `nonfree` license from `(guix-science-nonfree licenses)`.

2021-11-11 12:08 UTC, PromyLOPh commented on guix-science-nonfree/packages/gurobi.scm
> +     "See here for more info: https://www.gurobi.com/documentation/9.1/quickstart_linux/cs_python.html")
Please add a proper description what Gurobi is/does and use texinfo markup for URLs.

2021-11-11 12:08 UTC, PromyLOPh commented on guix-science-nonfree/packages/gurobi.scm
> +								   "/lib/python3.8/site-packages/gurobipy/"))
Can we use `site-packages` from `(guix build python-build-system)` here to avoid breakage as soon as Python is updated?

2021-11-15 16:14 UTC, falloutphil commented
Hi @PromyLOPh thanks very much for the feedback - I've added 2 further commits that should cover your requirements.  Let me know if you have any further questions!

2021-11-16 12:09 UTC, PromyLOPh commented
I fixed the indentation and pushed it to master. Thank you!

2021-11-16 12:09 UTC, closed without merging

2021-11-16 18:49 UTC, falloutphil commented
Thanks @PromyLOPh and sorry about the indentation.  Stupid question - what do you use for the indentation? I use the Guix Emacs package (indent-region), whilst it works on the whole, it seems to over-indent keys in package definitions.

2021-11-17 07:28 UTC, PromyLOPh commented
No problem.

Not a stupid question. I actually use kakoune instead of emacs and it also fails badly at indenting keys inside `arguments`, so I just do it manually 😞 I think `etc/indent-code.el`, which comes with Guix, has the same issue.